import {
  Home,
  Clock,
  Calendar,
  UserCircle,
  Smile,
  Shield,
  ChevronRight,
  ChevronDown,
  CheckCircle,
  ArrowRight,
  ArrowUpRight,
  Briefcase,
  Bell,
  Plus,
  X,
  Lock,
  BarChart,
  Moon,
  Sun,
  Camera,
  RefreshCcw,
  SlidersHorizontal,
  Share,
  Users,
  Menu,
  Check,
  XCircle,
  FileText,
  Globe,
  Zap,
  RefreshCw,
  Star,
  PlusSquare,
  Inbox,
  BadgeCheck
} from "lucide-react";

const MAPPING = {
  "house.fill": Home,
  "clock.fill": Clock,
  "calendar": Calendar,
  "person.crop.circle": UserCircle,
  "faceid": Smile,
  "shield.fill": Shield,
  "chevron.right": ChevronRight,
  "chevron.down": ChevronDown,
  "checkmark.circle.fill": CheckCircle,
  "arrow.right": ArrowRight,
  "arrow.up.right": ArrowUpRight,
  "briefcase.fill": Briefcase,
  "bell.fill": Bell,
  "plus": Plus,
  "xmark": X,
  "lock.fill": Lock,
  "chart.bar.fill": BarChart,
  "moon.fill": Moon,
  "sun.max": Sun,
  "sun.max.fill": Sun,
  "camera.fill": Camera,
  "camera.rotate": RefreshCcw,
  "slider.horizontal.3": SlidersHorizontal,
  "square.and.arrow.up": Share,
  "person.2.fill": Users,
  "person.3.fill": Users,
  "checkmark": Check,
  "xmark.circle.fill": XCircle,
  "doc.text.fill": FileText,
  "globe.americas.fill": Globe,
  "bolt.fill": Zap,
  "arrow.triangle.2.circlepath": RefreshCw,
  "star.fill": Star,
  "cross.case.fill": PlusSquare,
  "tray.fill": Inbox,
  "checkmark.seal.fill": BadgeCheck,
  "line.3.horizontal": Menu,
};

export function IconSymbol({ name, size = 24, color = "currentColor", className = "" }) {
  const Icon = MAPPING[name];
  if (!Icon) return null;
  return <Icon size={size} color={color} className={className} />;
}
